### ISSUE TITLE
[Bug]: VerbSnapshot is saved despite DB error / transaction rollback

### ISSUE THREAD

**Issue by cheyner** [hirethunk/verbs#100]
### What happened?

If I'm wrapping SomeEvent::commit() in a DB transaction, and there is a DB error that causes a rollback, I don't expect any insertions to the database relating to that event/state. 

### How to reproduce the bug

I'm committing an event with something like this:

```
DB::transaction(function() {

  SomeEvent::commit(...);

});
```

In this case, there was a database error (I had forgotten to run migrations) and so -- as expected, none of the events were stored, nor were any of the written models.  There was, however, a snapshot stored with data as though all of those records had actually been stored.  

I did a little looking around the source to figure out why this might have happened, and I believe it is because of this logic in the `VerbsServiceProvider`:
```
$this->app->terminating(function () {
  app(BrokersEvents::class)->commit();
});
```
I believe this call to commit() is firing and, because it is in the terminating callback, this is outside the original database transaction and not subject to rollback.

### Package Version

0.3.0

### PHP Version

8.3.1

### Laravel Version

10.46

### Which operating systems does with happen with?

Linux

**Comment by inxilpro** [comment]
This should be resolved in the latest release.
