### ISSUE TITLE
[Bug]: Conflict with Genealabs Pivot Events

### ISSUE THREAD

**Issue by adamthehutt** [hirethunk/verbs#103]
### What happened?

I'm trying to get started with Verbs and the service provider is throwing an error on line 145: 

```Unknown named parameter $model```

I've traced this to another package I'm using, [laravel-pivot-events](https://github.com/mikebronner/laravel-pivot-events), in [this code](https://github.com/mikebronner/laravel-pivot-events/blob/4aaa741996819e047c49f517ef0743e138ba9398/src/Traits/ExtendFireModelEventTrait.php#L48).

The pivot events package is adding metadata to the event payload, which is necessary for handling sync/attach/detach events. 

This causes the [handleEvent](https://github.com/hirethunk/verbs/blob/bd4a7b67b43462c2694af1e13b915c01e3ad5b4b/src/VerbsServiceProvider.php#L145) method in the Verbs service provider to fail, because it doesn't recognize the named parameters it is receiving. 

I'm not familiar enough with Verbs to have much to offer here. But at a glance, it's not clear what benefit you're getting from the splat operator being used on line 145. If all you need is the first parameter in the array of data, maybe just pass that?

### How to reproduce the bug

1. Install genealabs/laravel-pivot events and hirethunk/verbs. 
2. Add the PivotEventTrait to any model.
3. Register an observer for the model.

### Package Version

v0.3.0

### PHP Version

8.1

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by inxilpro** [comment]
Hey @adamthehutt — I think it'd be fine to just pass `$data[0]` rather than `...$data` — would you be up for submitting a PR?
