### ISSUE TITLE
[Feature Request]: Add a Replay Command

### ISSUE THREAD

**Issue by woodspire** [hirethunk/verbs#16]
My question is: in the doc you are talking about replaying events.

How do we replay events using your packages ?

I don't see any console commands for that...

**Comment by skylerkatz** [comment]
While there is not currently a command to replay events, you can create your own command to do this.

Within your own command you probably want to truncate the models that are created by your event handlers. If you don't, you may end up with lots of duplicate data.

Then, you can call `Thunk\Verbs\Facades\Verbs::replay()` and it will replay all of your events.

**Comment by DanielCoulbourne** [comment]
Thanks @skylerkatz 

Yes @woodspire there currently is no command. I'll probably add one soon, or would merge a PR adding one.

**Comment by inxilpro** [comment]
https://github.com/hirethunk/verbs/pull/68 will finally fix this :)
