### ISSUE TITLE
[Bug]: On Composer install of Verbs itself, "bugg" repo is private

### ISSUE THREAD

**Issue by markjaquith** [hirethunk/verbs#24]
### What happened?

Upon trying to install Verbs itself, to check out the tests and such, I get this:

> Could not fetch https://api.github.com/repos/DanielCoulbourne/bugg, please review your configured GitHub OAuth token or enter a new one to access private repos

### How to reproduce the bug

1. Check out this repo.
2. `composer install`

### Package Version

6f50d61

### PHP Version

8.1.26

### Laravel Version

x.x.x

### Which operating systems does with happen with?

macOS, Windows, Linux

**Comment by inxilpro** [comment]
I've removed it!
