### ISSUE TITLE
[Bug]: When creating new classes from the CLI, on Windows

### ISSUE THREAD

**Issue by WyattCast44** [hirethunk/verbs#25]
### What happened?

I was following the Verbs quickstart tutorial and ran into a bug while creating a new event using artisan. 

## The Problem

The problem appears to be on lines 75/76, basically when it checks if there is a path, it appends a '/', but for the first iteration, it is the full path to the app directory, in my case: "C:\laragon6\www\verbs\app\Events", so by adding a forward slash to the front it breaks. 

I believe the intent was to use the for loop to create any needed subdirectories which makes sense. I changed the implementation slightly to use PHP constants for directory separators and to use the Illuminate Filesystem. 

A related problem, while I was running the code below, I tested generating additional levels of directories, for example: 

```bash
php artisan verbs:event Test\\Directory\\CustomerBeganTrial
```

The path is created correctly, but the class name and namespace are not correct, not a huge deal. 

## Suggested Change

```php
use Illuminate\Support\Facades\File;

 protected function forceWrite($dir, $contents)
{
    // break the path into parts
    $parts = explode(DIRECTORY_SEPARATOR, $dir);

    // pop the last part off to get the file name
    $file = array_pop($parts);

    // rejoin the parts to get the directory
    $dir = implode(DIRECTORY_SEPARATOR, $parts);

    // okay make sure the directory exists
    File::ensureDirectoryExists($dir);

    // now write the file
    File::put($dir.DIRECTORY_SEPARATOR.$file, $contents);
}
```

I'd be happy to put together a PR with suggestions. Thanks! 😊

## Script Output

```bash
php artisan verbs:event CustomerBeganTrial

 ErrorException 

mkdir(): No such file or directory

  at vendor\hirethunk\verbs\src\Helpers\Stub.php:76
     72▕         $file = array_pop($parts);
     73▕         $dir = '';
     74▕         foreach ($parts as $part) {
     75▕             if (! is_dir($dir .= "/$part")) {
  ➜  76▕                 mkdir($dir);
     77▕             }
     78▕         }
     79▕         file_put_contents("$dir/$file", $contents);
     80▕     }

  1   vendor\hirethunk\verbs\src\Helpers\Stub.php:76

  2   vendor\hirethunk\verbs\src\Helpers\Stub.php:48
      Thunk\Verbs\Helpers\Stub::forceWrite("/C:\laragon6\www\verbs\app\Events", "<?php

namespace App\Events;

use Thunk\Verbs\Event;

class CustomerBeganTrial extends Event
{
    public function handle()
    {
        // The best things in life are free, not cheap. - Lil Wayne
    }
}
")
```

### How to reproduce the bug

- Install Verbs (0.0.6)
- Attempt to create a new event using artisan. 

### Package Version

0.0.6

### PHP Version

8.2.0

### Laravel Version

10.10.0

### Which operating systems does with happen with?

Windows

**Comment by inxilpro** [comment]
We're now using Laravel's built-in generator commands, so this should be resolved. Let me know if you still have issues on Windows.
