### ISSUE TITLE
[Bug]: Handle is called more than once when replaying events that have more than one state

### ISSUE THREAD

**Issue by skylerkatz** [hirethunk/verbs#76]
### What happened?

When replaying events that have multiple states:
```php
class UserJoinedHousehold extends Event
{
    public function __construct(
        #[StateId(UserState::class)] public int $user_id,
        #[StateId(HouseholdState::class)] public int $household_id,
        public bool $activate_household = true
    ) {
    }
}

```

When you replay the event, it is replayed for both states causing handle to be called twice.

### How to reproduce the bug

Create an event with more than one state.

When replaying the event you will see that the `handle` method is called once per state.

### Package Version

0.1.*

### PHP Version

8.3.3

### Laravel Version

10.*

### Which operating systems does with happen with?

macOS, Windows, Linux

### Notes

I assume this is because in the `src/Lifecycle/Broker.php` we loop through each events states and then call replay.

**Comment by inxilpro** [comment]
I looked at this with @skylerkatz a bit today. I think this is just a mistake. Should be a simple fix.
