### ISSUE TITLE
[Bug]: Both assertCommitted() are assertNotCommitted() pass for the same event

### ISSUE THREAD

**Issue by cheyner** [hirethunk/verbs#98]
### What happened?

<img width="510" alt="Screenshot 2024-03-31 at 10 28 40 AM" src="https://github.com/hirethunk/verbs/assets/146845/5ad04026-a5cf-4e08-89a6-6ecf55bf7322">

To illustrate the problem, I'm calling both assertCommitted() and assertNotCommitted() for the same event in this example. One of those two assertions should always fail -- but in this case, the test passes.

I've discovered this issue when testing against an Event failing an assertion during validation (and throwing an exception).  I expect assertCommitted() to fail in this scenario because event validation fails and an exception is thrown.  

FYI, these assertions work as expected during a normal event commit when no exception is thrown --> with assertCommitted() passing, and assertNotCommitted() failing.

### How to reproduce the bug

1. Verbs::fake()
2. Expect exception
3. SomeEvent::commit() that will throw expected exception
4. Verbs::assertCommitted(SomeEvent::class) and Verbs::assertNotCommitted(SomeEvent::class) will both pass

### Package Version

0.3.0

### PHP Version

8.3.1

### Laravel Version

10.46

### Which operating systems does with happen with?

Linux

**Comment by inxilpro** [comment]
Turns out this was a misunderstanding of how `expectException()` works… closing :)
